# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CollegeBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CollegeBook
  pod 'FirebaseUI/Auth', '~> 8.0'
  pod 'FirebaseUI/Email', '~> 8.0'
  pod 'FirebaseUI/Google', '~> 8.0'
  pod 'Firebase/Firestore'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'GoogleSignIn'
  pod 'Firebase/Auth'
  pod 'InstantSearchClient', '~> 6.0'
  pod 'Firebase/Functions'
  pod 'MessageKit'
  pod 'SwiftEntryKit', '1.1.3'
  pod 'RSKImageCropper'
  pod 'NVActivityIndicatorView'
  pod 'SwiftyJSON', '~> 4.0'
end
